language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION='^3.4'
    - php: 7.2
      env: SYMFONY_VERSION='^4.0'

  fast_finish: true

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;
  - composer update

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpstan analyse src tests
  - ./vendor/bin/phpunit
