sudo: false
language: php
php:
    - 5.6
    - 5.5
    - hhvm
    - 7.0

before_script:
    - composer selfupdate
    - composer install --prefer-source

script:
    - php-cs-fixer fix --dry-run --diff
    - ./vendor/bin/phpunit
